# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 464914b0020517fb1ae5f8e87a32787a7669585d92d3184d4434d372ccca492d82a8f316804f32fccdc02e8ebb5a6f78a0d7b33ef597f97fdfd351077859db1f

test:
  secret_key_base: d708c37ff63e683ab38fe633037ab98dcf1c5be0b611c450829e9cd03584f25430fd834cc356c1483b9ae2eb17b7f2ca93067e7e4eea3a86bad186b780a75b14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
